[workspace]
resolver = "2"
members = ["sword-tests", "sword-macros", "sword", "examples/*"]
exclude = ["sword-tests"]

[workspace.dependencies]
sword-layers = { version = "0.1.1" }

sword = { path = "sword" }
sword-macros = { path = "sword-macros" }
tokio = { version = "^1.0", features = ["full"] }
axum = "0.8.7"
axum_responses = "0.5.4"

serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
regex-lite = "0.1.7"

validator = { version = "0.20.0", features = ["derive"] }
thiserror = "2.0.17"
uuid = { version = "1.18.0", features = ["v4", "serde"] }

tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }

socketioxide = { version = "0.18.0", features = ["axum-websockets"] }
