[application]
host = "0.0.0.0"
port = 8081
graceful-shutdown = false
name = "SocketIO Adapter Example"

[socketio-server]
enabled = true
parser = "common"
transport = ["websocket", "polling"]

[middlewares]
body-limit = { max-size = "5MB", display = true }
request-timeout = { enabled = true, timeout = "15s", display = true }

[middlewares.cors]
enabled = true
allow-credentials = true
display = true
allow-headers = ["Content-Type", "Authorization"]
allow-methods = ["GET", "POST", "PUT", "DELETE"]
allow-origins = ["http://localhost:5173", "https://example.com"]
