[application]
host = "0.0.0.0"
port = 8080
graceful_shutdown = false

[middlewares]
body-limit = { enabled = true, max_size = "1MB", display = true }
request-timeout = { enabled = true, duration = "2s", display = true }

[middlewares.compression]
enabled = true
display = true
algorithms = ["gzip", "deflate", "brotli", "zstd"]

[middlewares.cors]
enabled = true
allow_credentials = true
display = true
allow_headers = ["Content-Type", "Authorization"]
allow_methods = ["GET", "POST", "PUT", "DELETE"]
allow_origins = ["http://localhost:3000", "https://example.com"]


[my-custom-section]
custom_key = "value"
env_user = "${USER:default_value}"
