[application]
host = "0.0.0.0"
port = 8081
graceful-shutdown = false
name = "Users Management Example"

[socketio-server]
enabled = true
parser = "common"
transport = ["websocket", "polling"]

[middlewares]
body-limit = { max-size = "5MB", display = true }
request-timeout = { enabled = true, timeout = "15s", display = true }

[middlewares.cors]
enabled = true
allow-credentials = true
display = false
allow-headers = ["Content-Type", "Authorization"]
allow-methods = ["GET", "POST", "PUT", "DELETE"]
allow-origins = ["http://localhost:3000", "https://example.com"]

[serve-dir]
enabled = true
static-dir = "static"
router-path = "/static"
compression-algorithm = "gzip"

[database]
uri = "${POSTGRES_DATABASE_URL}"
migrations_path = "config/migrations"

[hasher]
cost = 12
