[application]
host = "0.0.0.0"
port = 8081
graceful_shutdown = false
name = "Authentication Example"

[limits]
body_limit = "10MB"
request_timeout = "30s"

[serve_dir]
enabled = true
static_dir = "static"
router_path = "/static"
compression_algorithm = "gzip"
chunk_size = "1MB"

[cors]
allow_credentials = false
allow_methods = ["GET", "POST", "PUT", "PATCH", "DELETE"]
allow_headers = ["Content-Type", "Authorization"]

[database]
uri = "${POSTGRES_DATABASE_URL}"
migrations_path = "config/migrations"

[hasher]
cost = 12
