[application]
host = "0.0.0.0"
port = 8081
graceful_shutdown = false
name = "Authentication Example"

[middlewares]
body-limit = { max_size = "5MB", display = true }
request-timeout = { enabled = true, duration = "15s", display = true }

[middlewares.compression]
enabled = false
algorithms = ["gzip", "deflate", "brotli", "zstd"]
display = false

[middlewares.cors]
enabled = true
allow_credentials = true
display = false
allow_headers = ["Content-Type", "Authorization"]
allow_methods = ["GET", "POST", "PUT", "DELETE"]
allow_origins = ["http://localhost:3000", "https://example.com"]

[middlewares.serve-dir]
enabled = false
static_dir = "static"
router_path = "/static"
compression_algorithm = "gzip"
chunk_size = "1MB"

[database]
uri = "${POSTGRES_DATABASE_URL}"
migrations_path = "config/migrations"

[hasher]
cost = 12
